package com.mypetdefense.util

import com.mypetdefense.model._
import net.liftweb._
  import common._
  import util._
import net.liftweb.mapper.By
import me.frmr.stripe.{Coupon => StripeCoupon, Subscription => _}
import dispatch._, Defaults._

object DataLoader extends Loggable {
  def loadProducts = {
    if (Product.findAll().isEmpty) {
      Product.createProduct(
        name = "Adventure Plus for Cats",
        animalType = AnimalType.Cat,
        size = AnimalSize.CatMedium,
        sizeName = "Medium",
        imageName = "adventure/Adventure-Plus-medium-cat.jpg"
      )

      Product.createProduct(
        name = "Adventure Plus for Cats",
        animalType = AnimalType.Cat,
        size = AnimalSize.CatLarge,
        sizeName = "Large",
        imageName = "adventure/Adventure-Plus-large-cat.jpg"
      )

      Product.createProduct(
        name = "ZoGuard Plus for Cats",
        animalType = AnimalType.Cat,
        size = AnimalSize.CatSmall,
        sizeName = "Small",
        imageName = "zoguard/ZoGuard-Plus-cat-2.jpg"
      )

      Product.createProduct(
        name = "ZoGuard Plus for Cats",
        animalType = AnimalType.Cat,
        size = AnimalSize.CatMedium,
        sizeName = "Medium",
        imageName = "zoguard/ZoGuard-Plus-cat-2.jpg"
      )

      Product.createProduct(
        name = "ZoGuard Plus for Cats",
        animalType = AnimalType.Cat,
        size = AnimalSize.CatLarge,
        sizeName = "Large",
        imageName = "zoguard/ZoGuard-Plus-cat-2.jpg"
      )

      Product.createProduct(
        name = "Adventure Plus for Dogs",
        animalType = AnimalType.Dog,
        size = AnimalSize.DogSmallAdv,
        sizeName = "Small",
        imageName = "adventure/Adventure-Plus-small-dog.jpg"
      )
      Product.createProduct(
        name = "Adventure Plus for Dogs",
        animalType = AnimalType.Dog,
        size = AnimalSize.DogMediumAdv,
        sizeName = "Medium",
        imageName = "adventure/Adventure-Plus-medium-dog.jpg"
      )
      Product.createProduct(
        name = "Adventure Plus for Dogs",
        animalType = AnimalType.Dog,
        size = AnimalSize.DogLargeAdv,
        sizeName = "Large",
        imageName = "adventure/Adventure-Plus-large-dog.jpg"
      )
      Product.createProduct(
        name = "Adventure Plus for Dogs",
        animalType = AnimalType.Dog,
        size = AnimalSize.DogXLargeAdv,
        sizeName = "X-Large",
        imageName = "adventure/Adventure-Plus-xlarge-dog.jpg"
      )

      Product.createProduct(
        name = "ZoGuard Plus for Dogs",
        animalType = AnimalType.Dog,
        size = AnimalSize.DogSmallZo,
        sizeName = "Small",
        imageName = "zoguard/ZoGuard-Plus-small-dog.jpg"
      )
      Product.createProduct(
        name = "ZoGuard Plus for Dogs",
        animalType = AnimalType.Dog,
        size = AnimalSize.DogMediumZo,
        sizeName = "Medium",
        imageName = "zoguard/ZoGuard-Plus-medium-dog.jpg"
      )
      Product.createProduct(
        name = "ZoGuard Plus for Dogs",
        animalType = AnimalType.Dog,
        size = AnimalSize.DogLargeZo,
        sizeName = "Large",
        imageName = "zoguard/ZoGuard-Plus-large-dog.jpg"
      )
      Product.createProduct(
        name = "ZoGuard Plus for Dogs",
        animalType = AnimalType.Dog,
        size = AnimalSize.DogXLargeZo,
        sizeName = "X-Large",
        imageName = "zoguard/ZoGuard-Plus-xlarge-dog.jpg"
      )

      Product.createProduct(
        name = "ShieldTec Plus for Dogs",
        animalType = AnimalType.Dog,
        size = AnimalSize.DogSmallShld,
        sizeName = "Small",
        imageName = "shieldtec/ShieldTec-Plus-small-dog.jpg"
      )
      Product.createProduct(
        name = "ShieldTec Plus for Dogs",
        animalType = AnimalType.Dog,
        size = AnimalSize.DogMediumShld,
        sizeName = "Medium",
        imageName = "shieldtec/ShieldTec-Plus-medium-dog.jpg"
      )
      Product.createProduct(
        name = "ShieldTec Plus for Dogs",
        animalType = AnimalType.Dog,
        size = AnimalSize.DogLargeShld,
        sizeName = "Large",
        imageName = "shieldtec/ShieldTec-Plus-large-dog.jpg"
      )
      Product.createProduct(
        name = "ShieldTec Plus for Dogs",
        animalType = AnimalType.Dog,
        size = AnimalSize.DogXLargeShld,
        sizeName = "X-Large",
        imageName = "shieldtec/ShieldTec-Plus-xlarge-dog.jpg"
      )
    }

    if (Product.find(By(Product.name, "Frontline Plus for Dogs")).isEmpty) {
      Product.createProduct(
        name = "Frontline Plus for Dogs",
        animalType = AnimalType.Dog,
        size = AnimalSize.DogSmallZo,
        sizeName = "Small",
        imageName = "frontline/Frontline-Plus-small-dog.jpg"
      )
      Product.createProduct(
        name = "Frontline Plus for Dogs",
        animalType = AnimalType.Dog,
        size = AnimalSize.DogMediumZo,
        sizeName = "Medium",
        imageName = "frontline/Frontline-Plus-medium-dog.jpg"
      )
      Product.createProduct(
        name = "Frontline Plus for Dogs",
        animalType = AnimalType.Dog,
        size = AnimalSize.DogLargeZo,
        sizeName = "Large",
        imageName = "frontline/Frontline-Plus-large-dog.jpg"
      )
      Product.createProduct(
        name = "Frontline Plus for Dogs",
        animalType = AnimalType.Dog,
        size = AnimalSize.DogXLargeZo,
        sizeName = "X-Large",
        imageName = "frontline/Frontline-Plus-xlarge-dog.jpg"
      )
    }

    if (Product.find(By(Product.name, "Frontline Plus for Cats")).isEmpty) {
      Product.createProduct(
        name = "Frontline Plus for Cats",
        animalType = AnimalType.Cat,
        size = AnimalSize.CatSmall,
        sizeName = "Small",
        imageName = "frontline/Frontline-Plus-cat.jpg"
      )

      Product.createProduct(
        name = "Frontline Plus for Cats",
        animalType = AnimalType.Cat,
        size = AnimalSize.CatMedium,
        sizeName = "Medium",
        imageName = "frontline/Frontline-Plus-cat.jpg"
      )

      Product.createProduct(
        name = "Frontline Plus for Cats",
        animalType = AnimalType.Cat,
        size = AnimalSize.CatLarge,
        sizeName = "Lage",
        imageName = "frontline/Frontline-Plus-cat.jpg"
      )
    }
  }

  def loadAdmin = {
    if (User.findAll(By(User.userType, UserType.Admin)).isEmpty) {
      User.createNewUser(
        "John",
        "smith",
        "",
        "rivera.mj@gmail.com",
        "password",
        "(404) 409-0724",
        None,
        None,
        None,
        UserType.Admin
      )
    }
  }

  def loadGroupons = {
    if (Groupon.findAll().isEmpty) {
      val threeMonths = List(
        "GCSSRDDD","RSPQGCSS","EYDCSZXK","BKGNFSDJ","BKYRYQBT","YFTDPCHR","TNDUNSRA","ZPKUVEKS","VWYCJDMC","NFFYHCFR","JQZTUKVS","ZAPYBNUG","WMDFRKVD","YTZYKAMJ","ZRYHAZAN","YUKYMRHR","PBCZEMRU","ZZTEKWAF","VQADPWVR","WMQXTJKY","CXRHCKNA","MBJCVGND","KPDVCJVA","ASQEZCQE","PBPJRPNN","NGKSHSBV","FVDDGHJG","QSUFPZUB","KMCYBXFK","VSSDTVRJ","EAEMZEMM","JKVSBUTQ","SNZHYABT","RDSDXSBC","ZVTKJAKQ","MYMRQMCT","DBSUSDFP","RPSVBZTW","VRPJKTWD","CDVXYSJJ","PXTJYNXH","SQQZEQKF","RCPGVYPH","NRGZHXDA","ZHBPMYGB","VSACXKNG","EUFVCVKA","CWYWDCQQ","XYYYYXQT","MNRTQWRJ","MYMKFBQX","MDXEDSWR","KNTCUUKD","QGEYSXEJ","WYFCNTDP","RBBEUNUS","STWVRJZS","FDDDCVCK","STCDCCAV","UMQZYQTV","QNAXJQER","AFQASUFR","GXBJWMKH","FMZCNJNP","HXHPKFBM","XJSPDSMD","GFSNUGPA","CMKXJQXM","YHDDTFCA","KEAMPXSG","JFZPGYTU","ZHRWSARF","PYTQXBVY","TNGEEXAW","WGVZMDFY","TCMWUTXG","QJSKZCPW","RXBUZJEC","CXAEFPVC","TPBEKQSR","BPEEQXQG","PGMXKKNT","HCASUTPM","TQSYTNNK","VNFZNFSJ","RRJDPTCH","SYXSTZRZ","VRHWNSYK","YNUFTJMV","YEAYAUTH","SZRJZQKA","UYFVUNTD","QXSZBFEV","RKGXPHVH","BERVZKUH","JGPVFWXG","XUEHUBWK","TDYJVQWC","MHSSSHFH","DXRBBEWP","QEXJRNJB","CNYJVZYN","WCSWAJCH","BDRQHPNR","PCBABQNY","HYHNHUVH","UQZAXGMJ","RENAGJTK","ZMPPJKMR","GGWJTSSW","HRYFRQXY","RSFVRVHY","GHEGEBAD","MACDXRXD","FBTZPNTV","RASAHARQ","VMVFPWTC","QDNKKRTG","DNCSDCPK","ZDZENJED","KDVSVBRF","EXKQQWMZ","NZEPFGCT","REDXPJVH","PHPWAKGR","QBVPQSZX","WBWANFYH","DYTVDUVJ","PHFRAYTP","ZXFGDUUU","QJEUHPEF","CCMRKUED","SCCYYAMM","CECMWKAF","KZZTVNPA","SFJJDWFC","PHWBKPAC","YGUUEBRG","NPMPFCRQ","GFCEQWTB","PRUTGETJ","TNQNRBXC","XZWTMJMG","YVPGHTXG","JGBDFEWD","HHDXGANF","FHPSTMXH","XESNTYKN","XVWXTFMG","PCVYJMBS","XRMAPFHJ","ZKFPNTCF","MBGJRZNG","HJHRDWKM","TCCYMJYK","YVZPZBKM","WAYBFWBG","XAQRCDPV","FKGFATYE","RSMCHRUZ","WCCMXMKZ","UEDNSUEQ","PXXSVBZH","CXWNPZAW","MXXSUQBS","BXYZJAYY","RJNXMTVD","KREPZZAT","GEUGHPNG","FUYVXSQY","CZDWECJZ","AFWPVXGH","CFBPFDXD","NYZUETAG","HFZVDHRF","EPVKCMNP","WZHDZXHE","JGVBTMGC","FNKEGRTY","BAQHBQBT","TJAUPSKK","VWGUBUVY","HHGVXKCB","MWYYWEGH","ZJWMRRBZ","HATFVJDR","AQUXQHDK","FGCKYXMP","PFJRCUSX","FSZWSZTX","ZXSUYTMG","URGMXFSE","WNFEAVQZ","AFFHJBCS","CBDSMPET","EDXWPKMA","RCJQGFTQ","ESFDCMZQ","WFUZXBPH","GMHBQPAE","TKWTUBZM","UMWXQATJ","ETVAAQHW","GKBVPCFB","BWJGMQJC","NYPVNJWS","ADZTZNFX","JNSKYMAR","CWSBFCBZ","VNGTBJCT","XRYPCSAZ","DFMUEXXV","EDDNCGAE","EFDFHJSB","VKQTMGUA","JAJSQEXA","ENJGKDEJ","HVAUCNTK","BMCDBMRF","FSJGTWZY","XSFPGZHR","NDFVSMKD","UKPQBDDQ","STJGXVST","YTPNFQQX","WEKXUNNP","AVWWUVKJ","RMTQBEMQ","CVDYRRXN","RSFAFDRH","JETVNHMA","RPGBZUWF","JPEVVPBZ","EQVRPCCS","ZXYDXSZH","NZDEVKXJ","EHJRFKTJ","GBMMKGYN","QNPSSXUP","RASHCJJP","XKRXTJQW","MHRSVXFP","XSHHQMNF","HJZEXZNT","UKSBWJRZ","MZVVJUVM","ZWFZQKJQ","CAYYVRRF","YVMVHVZN","KPNMUGAT","YPRUMCFA","WNSHCPVH","BEZWFXRD","HAJKVVVP","EKSSQRNU","RNBPFHVP","JMFXTNSX","HAGTJZRR","UVPGWXMD","KSQBYWJN","RZDEWGYZ","GXUSTRVV","EUDUZVEV","JBACSHBQ","HESNTKGQ","XAAPHUAG","NSJRMCMJ","XFCBMBGA","MJZSPRWK","EEGHKFRD","QPECDSQY","HCEEGFRM","YRWNJXPN","UXGBHEGU","ZVBBSKYV","RWSJJPXG","EGWVJHMN","HGXHCSQC","XECESETE","DFBVQWKC","ZJHFTCHR","ZBNGUAMZ","BMVVRVCC","BTQQKTPP","CEPVABFS","UQBHDKSX","YTURAPRW","DWXCZMJQ","WJJAVRPW","PUWBVNTZ","QXWFKJRR","NCXGYFZP","MGBMRYPF","SSSGCKZZ","KDPQNQYB","GRPHDXVS","WCNSUEFU","WZQJKJRH","WYZJVPDD","KRQBYDWC","PDYXZVNE","ZAQKYEVA","GPGKRBEW","ZKTAXYRE","NRUWSCQR","KQHNRZMT","THKNNSEN","KCARKEKC","FKEWNCHF","NEKXZMTQ","TYDKKRHP","ZKBREYHK","ZBMZXTPB","RKVEMDVJ","ZPKVPTEN","UYYETKYE","BYSAWMFP","UBRWUXHE","NQMKRJPR","EVPKMAPH","JTSDBZKQ","HUXVBURE","XUJGZHSW","XPGPKUNP","ZVSGYEEA","MQTSZFNJ","GFVRHPAM","AKKKBQYN","RRUZGCTG","KGJAEGBE","VBDRGUWY","VNRMNKDK","NTUTNXSH","KHUEJQWN","WNCHKEEM","WDFKCZPF","MYMHRAHV","DXUJERPD","CKWNXUXG","ATEYUEDE","HTKCDBSG","CHEXDQAK","JQBUKEAE","YDXDFZFF","XTMESARA","KWVQVWDW","PYXKHMSB","YYXDVZRJ","KHPQDDPM","PUXRSAMU","GWVNNWDY","YRMCEGSB","THGYGFWW","PJKMNCSM","BTQPCEME","SYRPPCSG","JXNBKNXY","VAVSXUQM","BFUAVKBH","BARAXKAH","TZBXKBYP","JKDUGUJA","SCEWQERZ","YCKYVGMS","YWXJXFMR","NWWGJQYD","VSVUFYXN","JQDUKGDZ","PQBHAHKN","FDBWKHKS","KXWQKFHZ","ENWJUWMP","RWDXCHNE","TJDFYGXA","XTQHPCAV","UVBKYTDY","PYSYEGAF","NSYBRADB","YQPKQJBY","JRHCSMUU","MXMWYSJB","FZMJSKFJ","ZKYFNDFF","SAZBQZSU","SGKDMSYC","DDZVHCYM","AGXRHYZH","MSUAPEZS","NGAEDFCN","RHSBTEZC","TPAPPDUC","RDUVSCFJ","EHNYZQDB","HAVFKTCM","PNREPZBQ","AGKZHVQY","KANXWPEY","DQVMWUGR","VMZTEWGH","SPCUXTDK","PJBGKGHD","NYECVNWZ","ZBFXYJDQ","FYQKFPKD","QWKBVNKN","UQWCKRBM","GKDBHHPM","BAUPECHX","SNQHAFTS","XTDWFZXR","BWYSRFFS","KDWXFASP","MDARAKQF","YDEGTRCK","AFCVHTBZ","MTPGZRHK","YHFTZMKG","YUGCAVVV","KADMXRTY","KSFGZFNR","HGWMDWUH","PPTSRHGD","XFQVTCCZ","PWJSRVXP","AETKPBWZ","VBFWBKCW","TKTPPVKY","QMBGSXWT","FTNTKVWE","WVZAHMCC","VWRAQCUZ","FYGMCDFU","USBFUYAY","PMAQRKVP","CFZWUVQE","FVKEFNWF","KKHSXQHB","NBVSSYWR","GPUEAJRH","UEGVMGZS","EGVSNWQZ","FUFQPWRS","NVETUXGB","QTKTCYSZ","YKVYMBCV","XTZGGMPR","MEWUWRSF","FBYDVXXM","UYFJNGCG","CFDZEFEX","FCVDNKFM","SYVQWPCR","GZGRKNED","HGJHKTVP","QMAAEJUU","PUHNPAAX","NVVFXYYV","XXFRCUCX","PDCCWSDC","QBBADSDN","FXXEETYD","SFWRUFDM","TBHZZXHH","ZVBBCFQM","NZDEFMJB","VWCXVPJB","WJGPWBMT","PWMGTDAE","SNYYKUQT","KDNSYXQN","NJBVUTQJ","UXPRJJNY","NCCXYRJB","EVYWFEXM","HPYDWUBA","ZGBVTURE","CGNFSXNR","SNWUMBWE","WJKXYDYQ","YEBQWUHP","HFBWAGFP","VUXUDRCJ","HZJPWBQB","PCTKVVMR","GZSFMSAH","MYHZXCTB","GRNTTEFF","KVYPRYHD","KANFHWDE","WZPRJGMV","WVWKKUNM","NTGNUKGD","TKWBXZYS","YTQFRZEB","WGXEQDDK","SGWWUTEU","SDQUFPSP","DGJPZUCH","NYUFSPAZ","VZRGJBTR","BDZXWCUH","QKSRMSXU","FUXUDAZQ","JVFTJFQM","EYDTRMUX","TAVSXNHC","SYHYKYYW","ATPXMRKS","MRTTSPDX","KCGPSRVK","AUMSDEPU","ANFFBCFE","RTGCWZWK","BGZSQWUN","FZBSCBUU","YRJMKSRX","VDEBDFST","PRPGGKKA","JTFSAQTH","AQPEFDPE","UQWZGDZM","ZXGEGYFU","HYNYHXPU","ZCQXHYSV","VKJBYGAP","HWDNYGGQ","VMVEUBCT","HUTGDVQH","MAWSBHQX","CPBVTPAP","DZVRXGQD","XXMEGHUA","UDKUEUXH","ADDUVFAU","XZSMPTVV","RUSSHDFX","PUFUFCNX","VJYDTHZW","DZAQCCDG","UXDMZAEW","BWTRQVHW","RADTSYTQ","YVJWQVPT","WXCBUFDZ","KVWSESUF","ZXKZJKKY","RKEKFCXG","MAUWNKZP","ACASHXYV","MFXQPEHM","AJBQBPQH","CNXAZFAA","ZZDZJUYC","BQPSHAZM","PNYYVTMV","AWSJGNGK","VUGQEBKY","JTVWBRZD","KBZAHXYH","TGMZRHBD","BVPFHEQY","PZACVJTC","AGCWAQTB","WWNJVBCB","PCUXHUUB","ZENUASGJ","TGEXZUMM","VFJEZKFU","QFQYTTRB","AGNNHAED","ETQYCHDM","VPRMJFVG","DKNKBFHP","NDRUDUQT","WGWGTTPH","GJPYAJMC","NFMNCKFN","XUDNJSSD","PKKEWATQ","GQCFBGPF","KSYJPNTN","YGMUTUWD","ADSSQEPY","VKKRDPSK","ZXAYEJZW","JMRKGQCR","QTWSUZMA","PSZJKHSK","VRRNUQAW","QTKTTVFU","GGPRAGUQ","PCPGQKJU","QGDCBRWS","ARQWVRSU","XWNPAMTY","WFGMWVCN","FBEHYRKA","GWQTYQAH","EDPJHATP","FNTVCCAE","SXXPYAGK","GHJZSMZG","TJCYSVQF","UJQSQXUJ","CEBYHKEV","PSGPGKAH","BHWATNFF","QKPYHZED","YYDBBZUR","JVVVGSRX","RHXHFHWT","VFWGWWYJ","JAXYBKJZ","KVVDVEKX","VXWVGXFS","TRBSSPUA","PQYMBKEE","EAQBWZPZ","NUSZRMXN","ECXGCCWN","KHSRUHNK","UGYTVNMP","MFZKNKXQ","GSNCDQRW","UVDEGEWG","FKMABKWG","EEJJGGEK","HAWAZXHJ","KPXXXAAY","ZTXCYASY","BFWNHGTU","XBBQCVKE","DRWDAPJT","RSDMSFNN","HNKCWUKP","AVFSWGCK","GXCRZBHZ","HJGMAYKY","GEYUBSAW","EUZQWZBT","NBTZVFNU","NNJUCRZA","EAJUYSWS","ASVRGCTC","QNPFJNZR","WTVQDMGK","UTWBCYEX","BBFYPSXV","TQDCZSWN","DZHWHKXW","TNEWFRQQ","AFKDNJXP","ZQYEHEAX","XVKVDNBV","YWPYCJBP","JQZSPBRW","JGVTFSJR","HTCKKZRA","MDYDKUAT","RXEGBHAU","RJGCZXPE","XHRCTZTW","VQYNRNFX","CHVZAYXZ","UXZJFDMP","SZXJNHNC","ZBJNKMNP","TKCRBMWE","PYFHMSEY","PBSHWNRT","WMSGNFWD","EDEUZYTG","ATTYQQNB","FKZYNNXB","BCSZKYDC","EAZYAAXM","AQUWYDMD","CFAPYDCV","TKPDUUCJ","FPGTQRPV","BTYNUWBN","ZBJUZUBP","NZAKYARD","UAECBYVW","KVDAYUPF","RDXHVVTY","MYVMYDME","CCSMKVKD","ECYPSTZY","GWGZSNEV","DUBGPMUE","ERPHANVZ","PWPCNYAX","MTXWHNAH","NNCVFQJT","XRNFQXGQ","DYWJXZRS","WFSUGZNB","BZJXTHHY","XYPNVCRJ","QHYAKFRS","KHUKRMCN","QUJFMQDF","SKPZTYGX","KNWXVRHZ","UQJZSVMK","YHPKBXPN","CEGRNAKN","TSVDABQW","UJTTAZFZ","GFHHKCJW","AFCYVXBP","GYZVDVHZ","FDTJWSDH","WUTANECA","SYBRRJXM","JVPFMVXS","KDPFZBRU","WADGGMTW","RXDWURPN","FURNPZPE","HVNDSVAW","HZHAKXHB","YGTHYUTU","UUPWXVCS","UJYFJWHN","CKXPVHJS","JAJZGUYQ","KETQTCRV","BFZQTSMM","AYWFCRJG","EAHKEGSS","AUQFYDXC","EJBFYNEV","HQSXJEYC","NWPVKYQK","VXSBTPWQ","UBAEBZYT","HECGJHEX","ZDNFUUBY","UPXCQAVW","DTQUMKGH","PCNHUJCF","JXFMJXCZ","ADUZVCFP","TNCHKRXD","UUUGMHZC","VVRWUFJU","BYJCZWBK","FCMRPNXQ","UJXTEUZY","XRVFTWNQ","ADSUBJQM","YTQQFGBN","ZXQYPMXB","VSGHDZEJ","EABNSGEY","UXGZKWCQ","UFUDBKJB","ATHTRWZQ","SWUGTDAG","WDSTDECB","VDEBVAZC","YBBNRDSV","PTNUUGMW","HEBFEPTQ","YZZPRSVM","ADCMMFEB","XMRKWZDJ","VMDMUDYB","DRMXZBKC","TQHJBMBW","HATZSBEK","SESHMQCR","GCPFVMMY","FDFYQWUG","PQJPNBMK","UAFZERHW","HWTWWSRC","KGFARFKC","BTVFDNNP","AZJSGWCR","GVMGRJXJ","BEGDTBDS","PYSJPRGQ","SKMGNPHT","GJGYTMZQ","ZCHDWGFV","VTBMENSS","CUEFPSMB","HNGMKPYJ","JZZZFMJM","THEGZGNH","HDMYHKGQ","SZHVNWJK","FKVMWUNE","HWXKGTAW","CFVXRZFW","KBADKTAW","AQMSAUST","CQGJJHEZ","AUHPCDYR","UWGUDQZJ","WQAEJQXN","FNVUETGG","CDZRMSZG","XGUPHPDY","WQUDUVTC","HJTAJYPC","DZTSGXMB","XAYJVPTU","WMANJNPE","MDVEWYFM","PWCXYZPJ","GSNQSHRR","PCJBMMQA","GYZAZGSP","CXPHYKEN","YBFGPEVR","DTMMEUZX","AYGNFZSE","YDGCUGWT","RXEQNFND","PZVERVXQ","DXMSNKSR","TVQAYRJX","YZVKCADY","GQKHESCT","GKXFBFKQ","HQBKWBBK","GTCVEWSW","UNWXDPAW","SRMMYAXA","BVTBVAKQ","YEJPGKUV","CKJKFGVY","UUYPTMEP","VWTTDZEQ","XTRJZRNM","FBFFUMTU","UBZMXYFQ","EJRAWVZK","QMPFQKWE","JFCSVKAQ","PAKCZVRM","CPHZJFKT","UFMBSMJQ","GHRHPAUC","WHXHBEEM","RTREABZF","BPVCRYKQ","JVEDNPPH","RAGVMXNC","AAGRBPDV","QPCRCRCT","SVYXZTZE","SSBDZURG","CQKSRYEZ","FMMUCYSQ","VDVHGVDR","TVKGWVYF","GAVNMVHF","KNPGWUJB","EYVGQWQR","ZZUCCCVW","HHNDGPPA","NKBZGWKQ","DUNJWSKP","MXJGRTAQ","JPPGGURN","JQVFKYAN","ZQBXAXMJ","MBPCTVJG","UWSPNDDA","ADJADCXK","WFSJKMQR","PCGPJJYE","HTNFDNUN","JDHAHXYD","AUMANJGK","XEPUUGYE","CWXCGXEN","JYUENKYW","EGGTXKEU","WXSPBYDK","PPKHUNBA","NTTBBKYH","EAQPXQUE","VKRDUYUV","MSJDPUQS","UPJQJPZK","BHBQSEVY","QERTGQTG","PYHBQHPW","VEKFXEKA","UUBRTJTM","ZKKFHWWA","NFXJYSMZ","XDAPYPSY","VWDKEUBF","PSVDFTTU","UZQWPBMJ","KCHMCTFR","AUGKKBYY","BPPRQBQM","FASRFKNJ","PXAUUPZT","RHCJSWYD","RRVESCRU","EBHFQSTV","RDQKNZFC","DNQQQFKX","DYKVEHHT","FUTBXXPR","XSZANPJU","YFTAKZGQ","CXSMVYZR","MYSYYBVX","ZYMCGBNY","NXGNWZJJ","JCPNWYJR","TVBDTSZX","HCAXMEEW","KEAWEJWU","STRHCQET","CDTERFSG","FMTYZHCT","FDZSZQJR","ZJXWUBER","VWCMDACK","GUDDSAPX","DQSFUZHK","HMWNZUWB","VEJSFNUT","SZCGSUKR","FWCEXWPT","TRCDQTKJ","FJEXUHSN","KTFKETAR","EFBUYGSM","FMTCNZNS","UNYKRHGR","KSGAVSZU","TPPHXVGE","JRDFXCVA","CWEQTFPG","APGJVQTV","KTDESSGP","UQGCJRAC","AZZDCDRS","EHXCZNQF","RFAUTTYN","AWXYKJJK","REPAKJUD","HFEJKBSZ","YKGGMASJ","UQQRNJEJ","EXFXDDSR","JATBWXCM","RUJDXGRQ","MGPVBRYN","EYZVJHKD","QWJBJTKW","UAWMDCST","KDDUYVVK","WDFWXATB","QZSBXZQY","BZWZHPYH","SPYKNXCC","PXRKGWHN","UNAUEAYJ","ZKCYVEJB","GWXGSBNE","NMUMXUMH","VJCTXNFQ","YFHATCUT","DAQRUYPK","AJSUKDUQ","PRSJCXYX","ZKCKQKGD","FYRGEBAW","WASCWKHJ","CRBYTPAW","EEJWCMFZ","RARNJGPU","VDQBYCFS","ZGSTTZWQ","MMGRGTST","XNKPDWCE","XDSQMGWU","FCACFMGQ","CTGFDJTH","TNJHXPWH","PZUTKRBK","VYMCTMSR","WQUVSFQZ","YFKVFVTP","WYWNZYZF","DFBVRDZF","MAMWQURA","QYRQGABG","RRBWZTYU","FJRESEGQ","QXEMWSDX","SDJNYACA","FYCAZBNT","RQZBBVMT","UUEXGTTJ","HCYTVUNV","VUEGRHEG","GHZQRFTQ","XJDTVBXW","WEYBRYBB","WEPRYEAY","MSPEDKXT","JRPQPZFV","AKWKBKAR","WSSRBFQT","QYYVAQQK","YCCHRJFV","JJAVNPHN","TXYBUJCC","EQGJFBBX","NQPAKMSZ","TAEZZGSR","CBCWYBAS","YKZXZBEH","DDUMYSXP","GANMNXUJ","QAXSTRUB","AGUWTGKY","QGDVNBRN","EGACDADK","WQJYRQVS","PVWYGPPT","THKBVSYS","YZQNHZHV","XAMFUMVF","DNNPSBGT","KZHZUTJH","MKAHYPDW","GUJGGWYW","TSTCFACK","KSBGSNPZ","PMZVZVDK","ZDVATUGP","PAQVAKJN","ENBTFBED","BDXVQZMM","ZHSQBRCP","GJSPGXYK","WHCHBQQN","AYNEQBYS","FYMNVUUD","ZAWQTGWS","CSFMDTQV","HJUXDGBR","APYPMJTD","HVXYMYZE","VQCBHDDN","AFTQWQHJ","VQTMFASR","PNAFSNZX","BUNXNTHX","QYREDPPG","PVWVGRJJ","YXGNYXJJ","MSVTZUHB","DBEEUGWV","DHKNRYKC","RMHJUTDG","XXKNJBJJ","KRGUBDDT","SPJJEVBH","QSRNUHTE","CGCQVJNB","VKFCAWVB","ETQYFXYU","BMJKAKSJ","KJCEJVKP","YMRXJKXK","XVSDRYYJ","DNZDUZPC","TQRRGRFG","FJBZNXQA","UAZWGDBM","FJPBDFSY","BCTSABVV","TGKUHTMH","YYBJSTTM","ZTQZQWQP","MYDNMJEU","SHHZBGHK","WARCWNVB","DSBFQADD","PDVCVASB","RNHGVBJF","ZBABNZDA","PREYMWYZ","FYAEBUES","QBPHGPCR","EZMAWPDH","VGPHWQHB","WJUHVTVC","NMSUVRQJ","CYNRFARW","WHQRXXXS","ZSDENZNJ","MDRYJZRF","YEGJJYYG","YEWUDPSH","BYEVQPBP","PDQWJUEK","FGGPKXMS","QZQNXYPS","HXFHAVAX","TRKEJWRW","YVHZARMZ","DACMDUGX","QVWRWVXT","PNZENTHX","ZTSXQDQK","GRRBMCTT","FBUDAKRK","JHKVTWBX","KGTJBKBT","FAVMNTQX","GYXQCWUK","YJSZKRBS","GGDZSCDZ","JDNJMSCS","AGXUQNEM","FBSMYEVJ","RBNMQDTM","HSGDZZZQ","GFGNANNP","YHGDJENN","KPAMTFZG","QUCXXXBA","YMVTHZNX","NCFBSYTU","UDARWYQV","UKMNYWJM","JCUUHDQW","UMDUGKTX","JJEDFGAB","XCXTJCYQ","FQZCMFRJ","YSMQCWHS","SUGCKGVM","RSCSJTSB","QGFBWMBQ","BFJHPQKY","YBCBGKWJ","HDAXNDHB","WGXTRHAJ","ZVFJYXJJ","ETVHJCZG","CBGQAGTM","AWTMMWQB","JZXUQSUW","ZHHQVWKS","NANFVZFC","URARAADD","PZXKNYXR","NGCWXXJP","EMFJJFVD","VWDDKHDY","KHCHYUYE","ZGNZTTQS","BJJUKNEC","BRWUUBYF","WUYGXUHP","XXZKCZCW","VHPGWCER","JTMYDZAY","WMSPRVPZ","EBQNHACM","CATNGPAX","FZRMHDQB","ZJEBQYJM","SEZFURRV","VFDFPQNK","JHAKGRBV","REDDPFMV","KBXMVBFA","GHBEACYU","ZNHEZUTP","CTKWUYDE","HRRKPJQC","WQKRUPZR","GZCZDFSX","XZDJTQJC","ZEZHCDGY","ZJRBSGRA","YYPMMPZY","RXGAYAVA","VWXEQMNJ","GTEMSBSZ","WBXEXKVR","BFRXGPKG","YSDCXXYW","WSYKRJWS","KTBABNGP","MGUPNEUZ","FNHRSQJQ","SVCQACPQ","RVVEYAFK","TTQYJMGK","GQSWFUTH","MXYCQVVG","HBFJYUHA","JUXYFEHU","PXVRQEAT","JABQEABV","NSACTXXX","TKQCRCGV","EVHYSEHQ","RKVDZBDM","VFHRZYHU","GQBBVMCQ","QKGMCAYD","PBEXMDYB","GWCBGEGE","GBSHSTUQ","GDBREFSS","YJPCCAWK","WKKBYQMF","MJKDEQWG","CTMZGRER","YNKJTPBA","JVWNTJFN","AVHXMHSJ","NWZXYQEV","JSNRFHNM","NUUYAMRD","UDSKKVDF","XDTZWBDP","KCDNGMZT","KWEXCXVN","HGTQMPPN","UMNWTJWK","NSEBQJBA","AHAJFWRJ","PFDYSFDN","VHYDPZYK","UZQCQFMA","USNVVJCM","DYYQHCQP","ACYUDETE","JRAKPBNH","PMVRURQN","WVJVGDVV","QNGJRJJB","XVPJRAWW","VFWETMKQ","YANHSNWG","AZWVEZMR","NNGWTJAD","NVVZDKGD","JKJGPFGB","JEVTMMXY","JWGYXEAR","KXNZYAEB","CRMYVHWP","SBNGYVEF","GQXWTUBZ","BZZXRMGX","YWNWPNDX","EGNFJWBV","KJJYXFJT","ZYVMXWEG","YCHWJHYT","MYTSNNGS","NJFGSEYU","MDJCKVJP","RKDVPMGC","VSQYKSWV","JQWHEGHT","HDEMUUCR","MVDXHCJB","DNCHCERM","UGMFVSZP","YDZNAEUZ","QNGXXRCE","ABVVSAHD","VHFXSPSB","NQAQNQMM","VGQYYUYM","XTAUXPPM","DVZXANQN","DZRFEJKZ","PVYXUYQU","ETKQDCRS","KHZRUPBA","PZXCNWBY","VYCERBQQ","CWTWMFQT","XEMMJFKV","DSNZEASP","UXQCXDDB","QGFFAHCE","ZNAKSEMS","SMTEDDCE","RZXEXPER","FHFYHFTJ","PFYACHUK","XMGVSEAK","FTYYSKNM","FEFJKPKT","KFJJUARV","WSCGRGNZ","MAGMUZJS","XAXVAVTR","ZZYHYGGR","FPTWRBNT","NPDWJDEM","ATMWWEBZ","KEFBERUG","AWEZTHND","SQRFWUWH","EUXHBYZJ","DVSVXPUZ","MCZTJCRH","UBZFHBYT","XZYTWNEA","AZXVBFNN","RGHQPYXR","NGMCWUED","MSFVTJAH","KYHCEBRT","BPNZJVPQ","XBENVHVP","JMPZVYTV","ZYCAPHJR","ZAQVZFEB","RBJTXUMK","QTUPZJJU","BQRTFFEX","DUMRUHEX","KNBAKHYA","EUDPKDQC","HXCRMAAZ","TFDPQAAB","XNDQETQU","AEAUBXAB","KWZHDFBN","FGFNMYCU","AVDPDDJB","EWCAGHJM","DWGYZMKQ","VADQVRSB","UTJAQHPG","FAJUZYBW","XXZJGDGB","TEERJCVM","RKJCSNCQ","AGBYABPJ","TBXAMQZP","NPTAPGMU","GQXDCTJP","SQMYZFWJ","YGPECEFG","UCXYUZVJ","MBVMKBMB","WGWHCZQZ","UMSQSPED","FSAENDVF","ESYGDWWG","XGUABFQA","SYQWCEEA","XDBADTJT","TMVFZAUP","JNMHRWYG","SPXKJCUB","XSXCPKNR","QVDKXZYR","DGDDDYMN","MRRGDKSA","VCCTKMKT","CDMYPBQC","PQRRCFJM","RSTUTDNZ","HMVQPCYX","EZWEBJMQ","CTXUJHEB","QBMVZJSZ","TDTWMXYE","SXMTVCRZ","WWKFPQHP","VANDCJFC","UMCZGPMW","REWMWQYQ","RQNYTVAQ","WCCUYEXG","UENZBXXP","KEQRMZVH","MCYCUQFE","JQBXNRWD","XAZZETQS","SERQDNZW","RPSVMQVR","PQPBNZJB","ZYMQXJZR","NPWADZCR","FWPDGCSV","SCDUFPBB","NXYTBYKY","XUJFHUUY","KFKYGNPR","WQRTMTNH","APKDHDYJ","VGSRVSFF","DZRCZGVN","DAZUHVTJ","PNJYJBYG","PQNQGFKW","JTUKNEVA","UPJWFFKQ","MVTWZXVS","QJMRJSFJ","JEEUDSBR","XMTZRJJC","WZTBGEDS","CTVZPRKG","KKBMJAUN","DGQZXHED","BUWGBUJN","RVXYMTMC","YHCGXTDP","FKJDQBVN","DQRBTBBC","HWCVJQXV","TVEYCFBZ","BUUBYZRE","FZDEVFAA","NDFHVBDE","PBUFTCYZ","NDGWBPBP","PWFSFDTQ","RTDTEHKS","AZUYZJNG","ZNCYJCSV","VTCATGFM","NRNBVZKN","JXMXFBHV","KQUPJASC","VJNJPAMG","QACHQBBW","PAMNXVRG","TSPSPHZU","RCAPNMKG","MGHXQQXN","URGHQAED","NEJNRAKQ","KKCSMYTS","ZGEPTUGG","YHATTQDN","CXGTZDHH","TNNWYTZS","SZZDQEHM","SVRPDHRC","YJTXDRNZ","JKHUPJKE","ZXTWWGKZ","FYQWSHQT","ATPKENVG","XNSKGMMQ","GQFEPAEC","RXKGTSXE","PUUXHNXB","TDSVDXKJ","HMAFVMMF","ASKXHWCA","MZMPZBMD","UNYBBQGX","AEDJZCXQ","HRXWGSAG","XTESEMKX","VFZFEXPD","EMKPJGPR","RJKPJCZA","JGDQEQHE","ZJHPDKJQ","FUEZCRUA","CQTZZXKE","CTNSDEHR","DUCAGZVZ","FSUUWEQT","SEXDTBFM","TZRGKMTG","BUBAXXXT","XNDAWJJN","BUQNMKNP","JKFHXNGK","VVRDQQJB","CFFNAQFS","RENRCGBT","NVJPWSVZ","THUBEHYE"
      )

      val sixMonths = List(
        "CAYFKRPV","BVPGACUY","RRCKTSMN","BMWTWDAX","UQNSRRVK","YABBTGCB","YEBAZZFW","VCRCWBTM","MCVHUUDU","ATFHBXHR","MXGPGRGP","HDCQYAKC","SXVRFQFX","XCUJVTYD","GVHZYZPR","KESBRAHT","HVTAWECD","CANJJFEB","JQAMQWQF","XNUUVMJQ","UKGNUCUG","HQRUTNQE","VMNAUUSN","KEFEWSTX","JPJXGHMV","RTZAQUEP","EAAZRJXK","PTJKVWQW","BAKJUMGK","NPEBQTHJ","AZPGZPPQ","NKWGXRTU","QSXBTNAE","CKCGJUFH","NDURYYGV","XNBSAFVB","DSSJRYXU","XARHRPDJ","GASMXKAW","CTJYGWPU","MZFTYVPF","TPQFVFET","AYCQPQDX","CQQGQJXJ","AEFVHJYP","XHZPEMSY","MCBBBFTR","SVHHVAGF","AJJPGGYK","QZAQSKPV","ECPECYPS","WDZVUKYB","FBXFWKXC","ARWGZEAW","DHGSNVKT","SZCPMKNG","EHYSZNVM","RPBAEHEC","CJWBTCCE","BBEWTHKF","PZVTSGYK","YDGTFAZP","AGDJVEWA","MUBNXFHM","SBJJMKZZ","MHECRBHY","VJPAGCSN","JKXVBYBJ","MNQAUDEW","GBMXXMTK","BKSMHCFP","QPYJSQKG","GXMBQWBU","AMWXBAFU","AJPSXBWW","HUPPVJNS","USBRUSEW","ECABPFNX","RPUXVTGX","VFZEBDDX","YTSJSAKJ","RNFDQNZQ","SUZVFTUK","WHYTRXUG","WAYAFQST","GWPFKNBF","XTWMUAAU","BCXZTQEH","DYAACJNU","CPRVZZCU","NRVYHDTB","NSMTXFXQ","KJRVBADV","TNHWPQTU","TAQUEBXN","VVHDMRSN","MUNEUXGY","GPBGGNSZ","ZKMUQSFW","SCDHRFGA","JWNFAHZW","GTUKHEAX","AWNEDEBT","JEKFFFBP","QZUEEUEE","NKCMERJW","QDZCEBWJ","RYFRSWFQ","VJTBBWNY","CJZVKWSW","DKTZCTXN","ZFSQENWG","XGUSGFNK","MAQHZXFV","XFVJWHWN","SATQFZYV","XUFVYDPR","BMNFGCJT","SVMHVRFZ","FVXFQXVR","RWGNCFVB","VHSGRDSU","AXDRHKAZ","STTAJRNH","PHFRPADA","JJBKFKYU","YBFJPMTT","PDERWWMD","NTXUMJRV","DVQXGPXX","CRMEXNZQ","MEKBBTBM","FMQMRXAS","TPTMYQQJ","FHCWUUEE","ZVENZVJV","ZAQQGJKA","MMEJBVCN","BEZTUZDG","NQYZXEXP","XAYUFUAQ","GZZCREVK","RPYHUXNG","APJZTESR","KDZJYSQT","VZPJNDKJ","GVKEWGZW","NAKRBFWJ","GZGETPKT","WMVMWCTA","QKNKRJGF","YPDUWNPR","RPUXVCWW","SXQPPKYJ","ERYQBKHK","ASJRXJWV","AWKQSTGC","APPEQCXF","QWKGEBWH","NJBPHMEZ","QBSXEXUV","RQYJWYZG","PNQYWCDG","NNVWRJUT","AVJHTBWG","CGFZYQJU","RDCNVCBJ","VFZJRQTT","PMKCWAHW","PVKCVQND","SKTNVQAR","EUYGNYXA","CEQANZXC","HMMKKVCV","GGMVEAHV","TYCDTECR","XVJKTYXQ","VEGGKYHZ","ESNKYBBU","ZPVYQDSJ","XPKCFQRD","ZXSHRWWU","BXBJQDKM","AJNTBAMU","CRBTTWCD","CJXREPNZ","DYNPPJUA","MWBWQDKY","KFJJEJQC","YXYAVTAB","TVZGYYPB","WEGSRPER","HAENBHDE","RUYCAHQT","XYPMYSVZ","ZSZFNPAV","HTBXJKHA","MPWQGCPH","HTZTYAYT","DARKRSER","ZZEGTSTN","XPBQYSQZ","KFHDJDQW","KVNHCTYV","EFPFSHAC","FMPUGMGW","SPJHHVUH","QNVYEUBQ","YXJUKNGR","SSTXQKBM","CRBUPRXR","WJJYHTGH","ZAGRWYRG","RBNKRDWV","ZHFJVXRS","PYRQVCXN","JXTGSMDS","MQYJZSUG","WCWFSPVF","MTPJGRCE","NGANPZKM","GURKKWVM","SRBDNCPC","BVXHEARE","SGPTVYPX","EASZEPMF","BUHFUJMQ","SUXDPXHD","BWCQZBND","ACTHRJMP","PWEJPVBY","THBEQGQH","NZUQAYBT","JNVQPMBH","ZUPWUHJP","CFRGFBPU","HGWGPAXY","FMCKYTKR","ECGVJSSU","EJVJHCVU","HXQXGARC","MZNUQTGQ","BSGKDPXA","NYKQUXEN","ZASMJMRW","VZMSGQXW","VEYABABJ","YFBKMADY","KWUEJQRP","TWEGMTNJ","MSZJTCZQ","WNQTWAZJ","UCSDTJMY","KNYUHTVA","MRCDYYQC","RUHHANTG","WRMHRCMR","GPGMXYCT","UPTRHDAU","KNBWXPJT","JCYFWUKR","XPPGTGPD","RVAYMMCW","VVXBYMFT","JDYJZNSH","CGSSKYCR","NPWEQFFA","EYQHWHKU","RJZGAGZG","KBKHQGVW","MUCEPHJY","FWGXYQGP","BYPUSNRG","SUCMPVSG","RTFSUWMK","DPNMQKJC","CGVQUWST","GRQPVXPX","TVAVHUSQ","MXKBSMKX","JGSEHXHC","CGFSRRJU","MUABHYTQ","TCPRTSBZ","CPTKFTQB","KVWYBPBR","VHSFMVXE","HZCHZEQC","QVPDPPRE","EJNMPBXK","WFPWUCEV","AJCCJFYU","JZRVYSKE","WEUXGWME","UVWJPGSR","FTUGMKNJ","EAZXDNDK","CUPZAWEH","SGKFFDZU","QXGKABNF","AWUQNUXM","ZNVUWVXJ","HARRHSRV","EWDPYWBD","VFJMMDUY","TEUUYBRN","ZWJAQANF","HHWPQBFU","GDXMEQZV","WDHKUUDX","DPVYDFJN","YYZNGHMV","ZVUZXWWJ","ZFQXHNNW","AKQWKHMT","QFUXHPCC","YPQSVDQY","UCXSZJZG","GGPMUTSG","FSWTHDSY","HZSXVAAH","VVKZXVEU","RDGHPRRV","WWBEXYBR","CJZYYJJG","QNHAXKQX","NKWKDKWF","GNRZMDGR","KJPZXFJC","QNSVTZTF","BYQDGQQH","UDXQQQWA","YTFCWVPX","VXGEUQKN","PQAYHBNM","GEDJACHK","UEPDMEYB","VMWXUMJY","CAWNBNAY","YHZANEFJ","JCJGBJNC","KRYDHGDY","GTUEAQRC","KGPHEECM","HCKFHQBU","DEDXMWEX","NSRSTNMQ","HAGKRDJV","THBFFAWH","QNTVBNRR","CUQEHTUT","EXYKFXAN","MGKUEUTM","DKJEPREN","NTWMEZXA","YKYBHGFT","EDJAFWMR","PNDFCDRX","EWPHVYMC","NFNHSWRG","DACNQHXC","APPXDXWC","VAUMTHPE","JYQHKHYZ","JWDJXHBR","PYBEHRYS","FKBMSDEH","YWDQHDVF","CEBHPDNH","BMJASDRJ","WXVZNQQM","CXJRUTPU","FXMQJGVT","RMKFFVQZ","YXBWVFAY","QGHWCAKE","NWYWYSSG","WJNHSZNP","CDVQVXFE","NHDHVNHZ","VXRWQKYQ","ZBDDPNTS","BSYPYGSD","FPMHRJFP","ZQQNJDKA","FGHTKSFX","WQSUXAVD","WGAVAPFR","YYCYGJZF","CADHANMW","YQRGKRJQ","SNJHWDEF","XRYQJZRT","FEUCMAAK","VTQWGUWK","ECEKADUK","JWCKSXMC","PHAEQKDR","ZGUVNASP","TEUCVYZT","PTBXJWYA","VVACDSKX","MNGHSNWU","CBXUQJFH","PCZXSXKG","HMTMPESG","CWUTWWVK","XDEEUMAC","KMGMUDJU","EWWCEKAJ","SPFVXWUA","FAYNKFGA","WBJQNHBY","RUCGRGHT","YBRSHHHY","VMCJTQSY","DTMTPRWB","QGDSQEFA","TYMUTRFJ","MZKTMDWW","SAREPYAM","QPERZPSU","GAPHVRRM","EFYREHHF","EKXEDYTS","HDRXJVBV","QXKKUDXS","RZXUUJES","PNDRJNGU","RMTEZGZT","UYXRQZCD","KKRNHVUG","MUKVFNTU","FVXNXEJD","CACMAPEW","ETBZUZNX","NMUBXPJB","WEGCKCBJ","RUZAZMCX","MYJVGTAM","WKMZQKPZ","EVQUJQPP","WQATTDUU","TTFZWFXZ","WCJXKTYW","FNBJEDNN","CZCZEFDP","DTCUASQU","YWJYGSUM","XYDURKEY","WWCEAAYV","NAUJMHYD","CXWWEYHN","VDBKDWMD","QCCFXYZJ","TXSHBXCA","RBMGRYJW","ZAXZUZSB","EQQYHRPP","ZNGCXVTE","QQMTWGJH","UDDCRFAF","YVDKRBHJ","PXDBEHEJ","TVMAMRKQ","SYSWNVAJ","ZFTUHTNR","HCZXSWNP","BAEWTEBG","YGSAMBHX","EWACPNCF","PFSEZHNK","ZTJDGBVX","WAQKQSRQ","PQCJQTQT","VQJZTKBC","FXMHPCWK","SPDFTFFG","NMCPSGWQ","PAEXYWTH","CZPVZHUK","EFUEYUYH","FYSCTBCQ","GABSSYAM","NWYXJHNE","RZVRCYRN","UZSRMBRN","FEFJWSWT","WEFNVKYK","WFCYVZSZ","FYTYXWQK","KWAEQCJU","ENRGPMZK","FRQREFTM","EXNFXDHS","GFHZZBWT","SRZUPCNH","JBRXNUQR","GXZVMQNB","UFVWQYXE","ZSTGMGCD","BJHNYEWE","FWCMPNFM","QQAUGRZU","DYABKHFB","KRCUYHRY","CKDCVGZY","HFDHPZES","YAYXNPHR","DMMKUWNM","FDAWNBBR","WHQNUMYA","UYDGRJJD","XMGYMFGK","YVVNEKBD","JTJJFPWM","XDFHRCVJ","VMSWHFQD","XCFFCGYU","QEZFQWEW","QKTVPGND","FEGFQARB","GCFDKVEV","WKVZCXFU","SDCADTZA","GGCVUQAV","VAWMAFPK","QAYEPQRC","VXCCUUNV","CYKDPFGD","XURJZDGS","AUHXKMJT","DNUBTXPA","ZRCGFACR","GRACVRDP","ABEVKDVP","FETSUDDG","QWZFNCJP","CXPNVBYN","YWMSCXVM","TXRRNFBV","MQMZTXRW","PFFVPJDR","QZNKFSQK","NKYXXREA","PWYVHMNG","PDCAFZGE","DQRGCFDW","VGTAAZQP","JWGJWDUR","PZDVWZPG","MMMFNXUQ","YVHEQRGT","ZHRPSPWB","ZCCCQEEA","GUAGUKQT","VMFZYSBV","JKPCEQHV","YVDQGGWV","KCEAYTYE","MVTUJQYS","GMHJAJGG","KSVTCWQP","GRGKSAAW","XFQMABXF","SVZWBFFP","VBBFQWQQ","CFQGBHTR","QHAJQPTS","SDZGQEPB","WYUFAVHS","RSVBKRDV","XNTHHBJF","HWWAJEQE","ANQMGRKH","UXAYKKZW","GRQDJJRJ","ZSVXGQRX","HSRMCJHH","YWEFYMNH","PARNFBJW","KHQMEDZN","JXZUVUZS","DAFBEYFW","WHSGXWAJ","AVJXKMFN","VTNTDEUR","APXSGBDY","QDYECTRH","ZXEHVYXY","YVNYRWAH","SDNZNFBE","FJHHKHYC","BSPCEYKR","ETQVZTCK","ACWQXCZZ","YPHVDZKR","GTZHZQMF","GZTEVUXT","TQVWQQYZ","FXXTGUNM","JMBVUMSV","VNKTRAFU","RTUHCXKG","JJGAKCHG","XQJZEHKG","BXPDTMUE","QDTEDVUS","CBPJUDMG","ZZPYETWM","EZYMXXAC","MGGVUAHS","FUVTNDWV","XRPWHUSJ","DTWJGQJX","MPNMXSBH","CCAJBKER","VAWJTBAU","ETXXSSWN","KCBMXTRY","DJPHKTNC","CXKCYUCB","XDBVPNDH","URHXEFWG","ABEAQEAF","TCQTYCJT","JRBSZYEH","ZUHMPTDW","TZPXPHEP","USAPMHWP","SJXKTUTU","ADTRYMAP","HAEGPWHZ","WVRMXWAE","ZNHKHWBV","WSTJRHZR","TCRCRGQN","NJNJJAZQ","DNFACXXE","KVDXYZEH","ZDJQGQYT","KQNGERGU","MACQKDSN","KRRSNVXQ","TVFSYTTP","FYMSQFVY","MSJVCTJP","DXWXVGHK","ESPUXQXF","NJYZBMPF","RUUNTBYE","DRHRZUCP","KUECZMFX","CUHEMTEU","ZTHMGEUS","CNDBSGPU","DMYJTXSH","XTGWRJYH","EUTRTTKS","HBGPTVWR","YRQFNJQD","KXMAVADT","GRVGPBWF","CPFBJPAB","VGJPKJJX","NHYEQRBG","KDURYWAC","DHBCCDRP","JPMCQUEZ","SXYPVQVY","VQMQRDPS","CPNUHKPH","UDVEGNRP","ZHQKECNB","JBPWYMJY","NCZNVNYJ","PUASZEJN","USUECKTF","AQSHWWDV","EHAWBCPG","HMAYKYGQ","RUNKYBXD","ACAVQEWV","PBBXBUGW","GRJNPJWQ","ZKPMAZUP","XCYPXVQG","XBKGMYUJ","VRQTPFHB","GQZMYFER","FYSXEXUC","SWGZUXTC","EMGSAZTD","WMRPUPDS","XGVHRQXH","JAZHGWRQ","BJXSUHRC","MNKTVVUQ","FRHWCUCR","XNWFPYBV","ECCYSTYM","TNDHBHQR","PRBNKQUG","EWKSUXKA","BQGYYJBD","PTRZCSNK","ZWRWZZKB","YVDQWWSB","GVYGXTWQ","ERTYKCKY","FHURMVTN","GZJKMJCH","MGDMAVTH","QKBCWQVN","UBVECGRR","NQCYNTVV","SMBHCQUB","JNDHWWYJ","FNTBRUNS","AAFWVXJX","JFSCBXAT","WCPESRZH","CQQTWCDJ","GRSPKMPC","SSXKBUJW","HHMYBPYW","TVSZVSGR","JTSUNTFY","YCKUFUEB","EUBJSSAN","KPBSQQYH","GMMZNXEZ","PDSZHJKW","JDRDCGME","TEBVZTYH","PAVRVCTY","DNKNZHPU","XKPGSRCW","CBAHSGRY","MTCACQDC","BYXXSZQT","WGANKPWB","RDPHPQZM","MVDQUGEF","BPAQDNAR","FWGGWMWB","VKHKKGJA","KJGSSNTH","RWNTEXMD","PENQWGZS","DKESBGYX","KFNFPWQX","UWAPBTNM","VMHNUQJC","QRTHKGEX","XVTAQEDZ","SABBPXNH","YYXEBPAQ","AAPTFFPE","HXSJKXCR","SUGXKXPU","SAVRESPK","XXBZFFER","VPKNZEWM","YMVNTKPT","JCCMDQCM","MVGAJKYU","UEGADSCG","SSCWGMCA","KGGNAVFJ","NWXQMARX","YMJEASZT","NXKMUPMD","XQBGAFZC","XBQXTMNJ","RTQENGFE","TVMBNVGT","ZRFRKMNW","JAYGZDBF","EMGVSWQR","MYEWXHRR","XKDGQKZC","CEXHDTGZ","TERSXBHV","FMZVFCQF","EMRKFASV","FWRSPHRJ","JSZYZDBC","JKZKPHXT","CQVPMDEK","KSWWEVTN","HBRPFZWQ","FRPYSZCY","VERGYNJH","UUHENWEA","RTGMDUKJ","WHUPFXUB","UFGSNRBY","VGTRNBHN","NVMDZNJN","KPWHJSCA","PZJKGHHZ","RAWHEEAH","JFHRVESG","HMHHAHCQ","KSRAWMZB","TZYXKKVE","PFDAGDGS","NYHPQRMF","XNCGYDGM","DNYWDYJE","RRWFXRHA","XDNVANTC","JRNXWXPZ","RHFRYZNH","GRCMWSMJ","DGKNFKWN","CTJNHVYJ","WHSZPYPC","MWDSMGUD","MDUWMFQV","BNYDNKNT","TKFXHVWD","XGDQZJVZ","FBJUHJDA","RWRNXQFN","SXFCFZCP","EZMNEWEF","DSSCSEHK","QTWPNBEZ","WVAJFVUN","XTGSXAJU","QMGPXHYB","PEYFWCSF","RQZUMVYR","UWBDAHQE","VMJXURTC","RGAVBHVM","PFSQMUUY","JDKXWNGC","PAGNMTUK","ZJHNKDTD","FXFJRWBF","WFDFGBTM","VSKHYRVR","MBTDZBAB","FAATXDGX","VRVAZNSB","HGUPMHYE","WYQPZBQR","VFWRKGEQ","VJCKPTJM","PRGFXBYP","QVUMJEQN","EXENCPDD","ERHGUDGQ","FRXQCTSE","VAYYSPWK","GDEYVETT","DEQBHQSH","ERBWAEZK","PBMZHVKW","UQYDPZHW","VHDRVHTH","KGFKUHWP","TTMSJDSK","MXMQRKPS","DZTNYMGV","XSKHYBJX","ERBQVCPX","NAEXGHHQ","WVAZNZXA","WKQRZCQZ","EMJKGYYP","CXQBWPWM","TXXCBTXF","NNFFRTGE","SMMUYDKW","FGXEFDUF","XXZVHPGE","WHHRDYVY","RYGSMGSV","CHENJFQN","XHCHWCAA","BJKGVZUZ","TUFJNJRQ","WQAPBERQ","EERDHKPD","SGHMQNRF","JJAFKZUN","JXWBADSZ","CCNYXFFW","BFKMQKRR","NEJMBFTM","MPUQGPDQ","BTBGXCMR","NMZKGMJR","QSPZXAUW","CJZWSHRX","HDNPKJXE","PBJTGTPQ","QMFTMDNK","AEFZFPYG","EYRBDWFJ","SZMUCUJQ","WDQAABTD","BKEHUUEP","ZEEVUMVB","XUKDEYWR","XNWBWJGJ","NCGUXRFH","RHJBAWAT","EUAZEYCY","XKWFWYAA","RKKNWRKX","EYSSNEAV","TGGCZCQB","UYZUMJQB","PZPZQHKW","UQASJRYK","FKKRQFTN","WAQHWNKR","SRSFXDGU","CQJXMWFF","HJZYEQAR","REDNYMCC","PATJMKMQ","HAPNFGCA","AXJKAUHK","MZZUDSCV","NAYTJETW","HUCDMUFY","KXXJAZHC","YRYZCMPX","EABXTZNB","JFBEUQWS","NBVZFHUK","FFVGHQNY","DHVMGANA","STTTAVSA","HZCKUUDK","FWYJYBJP","XTKEXMSU","BBFRCAJH","BVJXEEJA","VMDKPKSS","EYTTZMCK","JRBAJNZU","QHEFCRHC","NNTRCNQF","YRXBPTRV","TQATJPKF","DXQBQPHH","JXAGAVUG","BQWANXVR","ZSGKPFQT","XYYWDVVR","AFDGYBQB","NAHYQSNC","FQZXYMSM","RBCNUPGB","CUAZYDFS","NWZKMTWU","DXPYNHRP","KXUDYYTE","KFUSMYDR","RTYZZRRR","DHWXTHFW","JXPTDPVW","WMXHMPYC","ZDBDCZEJ","BVVUMPHQ","ZMQGEBQV","DQDNTWGR","VMDFSHCY","FJKBBUTY","JUEATTEA","CSTXQCAX","WMRRCEFT","VWGFXNGK","HDKZBHTW","SZPUKNGU","FMPDCVDF","PJKGMUPA","GPQNVKMV","SUBFPMAM","JDSSDSHK","RRKEUEGC","MXPBRQXD","NQTPGVCZ","YZZVBXJN","EYYQCBGX","FQWRCQHE","FGZSARCV","SVJCWHKJ","YDRXGXNA","ENTYCQHP","SNGMYBSY","WRNKYWUK","CFXYEVTJ","BPQMVHNU","XRGHENYV","YBPVNACD","RZQVQJHT","PCZVGHDK","XVDXUHZK","UNGPVQUT","ADVMKHSK","WFGXZFCB","KXRMCDDE","SYGURZDF","QACHAQSX","GNDYQSVG","VFGENMTG","DQNGPATC","CPSTEDXS","TJXHRANB","JKDKDQFZ","EJPKJRHG","HGQTEHDS","SQDJMYBH","HRVUCYBE","KZNYQTPH","KCGQWNES","VETXSSBV","SSGHAHJU","JCHEGHQJ","RFMENWJX","HAFYWCWE","NHNZYBQT","FPVUKUAS","EXFZWWKN","CZGCYDGS","KHZXNNEX","JDPACRBP","ENGKBBBC","GMBFCKFE","CCDQXDQJ","VMWNGPZY","KGCZNJPG","MVVJVXGJ","MGAZZTFK","HPGMZZHZ","VPETEPYR","PPRREGTE","AGYZNJZR","XYHPARMB","MHYBZXBW","CCQSPVZP","ZWAYJXEV","RDVZSYTW","CRQJXPSJ","SGQYCTGY","QWJYFQPE","ZYHXHVAR","UDPTWNFN","TEAFQPAW","RGXDEJCT","QEWTCAKJ","BKPQPASM","QJCKGXUK","FCGWBCNH","BMYFKYUM","ZBRVJYBS","HZHXAMHE","UCPQCPSK","USKRESEF","WGZSNDAF","BVGDBEXT","BYGAKUJU","JMVDRCJD","WMYQNGYG","MUPPZJFF","ADBBECHZ","RAEVHMCK","NSBKSCFY","YTSUQPXA","WQZBFJBH","DVHGFSAS","MJDCCEUS","YMYZQWNV","XTPXFYFE","THMUVCMG","MGZGTRET","BRXNUWKJ","SUWTXMPW","EVGKFWQS","EWWSFAFH","RSBAVDUN","WGGNAJFG","GNNHQREB","SXMUVTAV","VBHANSMU","FREPBTHU","KYVXUSXU","HAVHZMTM","VEAPGGBZ","KHCAJCKM","WPKRRFPP","KVMNXFZR","ASUAQXJS","VBQXHHPE","SPFAWKYD","GEQVWXPH","ABVANYGU","BWRXWVJH","RQWZBKFC","TFYKTXRG","KGWBHVNT","GFZPHSEC","YQNNBARK","HRGYNCTT","VCWTQXTG","VSEJPUGU","MFRFYGXT","GDHPBZYH","EWKKPVHJ","FJPDJAPW","JXJNBXDN","ZYXJQVDH","CJZXHZPE","NYMDGPSW","DJCBRPVS","RGURWXMK","CGFNVRQZ","CZDNZNKS","SHFNGZVP","RPCPDFVR","KDSMXDUM","VJHGCVDY","NAUCWXEY","GDFHEPXB","CJUSCXNT","RJVFZFMA","DJWPQXJM","MBWKANCX","KBCKJADP","XFKVTJZP","WPGZNQDM","YJVYABSZ","UBDNAPQG","PHMKYXQZ","AVEAWMGR","XRKGWJQB","YYDNDQCB","PFVDPUNW","KPEBWMTE","NQQGFJJT","KGANRNBQ","GGPVPBYY","XWMPKZSX","WKQYYFZR","GUVNZFHG","QWBPJNZX","MSRXNCYK","XKQUXNNR","QGQSZXAU","ENEKKUGP","TCGXSNER","SPRVUEHB","ZGZTDCMH","JZACQMRZ","MCZMVFJJ","VTAQVRRS","NFVPGHKE","UJZVHXUM","YTPWKBGN","VHQCAQNU","KRUSMRZM","JWNFQXMW","ZZWURMJU","QFXPPDJC","PMBCKBQN","DTQEBXVF","MJMCHKJA","WJFBVSQZ","QYNKVHSF","VCWTQQJV","GMJJYDFB","XVBMTUNM","VWENCFCH","DHCQMGXP","QPRCGNFM","ZRQHUVME","RUZKMPFM","KWGMUJPE","GANJFXSX","UASXQCUD","ZJPKHAXF","TMZHURDV","DCJGFCZQ","ZAVZPDFW","SHJUVHWG","WACFXKKJ","NJSEYPMM","RAYBBRQK","ASUHQRTN","VXBJGFUT","ETDYMBKQ","ZMUBYABM","EXKHPPTC","CUWPSSZM","EZYDXJAC","UXBTRPRP","TRAYWKPT","ZDMGDQUG","ENBCNVHS","GKFBBHWH","MCUUKTTD","NWSSSSCV","SPRTAHHQ","CZZARHFN","KMQTEYEM","FASWWVSA","NSQAPDTD","JVRTNBCF","GXWQTPAH","ETJZEAMW","NXRMGWNU","TZMRDVEP","RFFJQXEK","RGTZBYQU","XESTNQNN","ENNTNTDY","TBMNWTCA","GXHKTKYR","GTDTTJAN","DDQYQKKU","RREVCAZM","WJSRUNNC","ZREZRNSH","JHBEFZGA","VGCZYHMC","RSMHTKYA","MTYMWJSJ","EUBQGMFV","VANFJVCD","RHQFAWBJ","PWVKXPRD","VWNZXHXD","YXJDMCER","UTSKDPDV","XUURHXDP","NEMYVZXQ","RJVHHBGP","DJAFDZFN","YXFUNMGP","YSVZFYPF","GGUWEDSX","QAZBFFGB","TAXHCRTJ","JFTMTPHB","GAJDAPXE","CJAUUYMX","NVFNQURS","KAVVWXQP","GRJSWUKP","WWAXDHTA","PSUDVHNA","YBRCXBWR","FJFSPTUY","TSANAJST","JHDCGDTZ","SUECSJQQ","CUVJZKAT","VBPWFUTT","ZPPAUEBD","XCCSGMWA","RYPYXYMA","DXUQNFKY","QNCRKXBR","WVVKQEJW","MGDZNEHC","HCRJKKXU","BXXSPFJJ","GDAEASWT","VHMVTASY","KQVVFDPY","ABXSSKDG","GPGYXGRB","VBPQVGGU","RBTZKYUC","MFFBKPPJ","XBBUPABR","KJYVWFNR","BYFPNCTM","XPBFATVQ","BEFNGTHK","VXUVFZTB","UWEFQPVW","SNDACDSK","KKPQXCGB","WFXUNPUP","BAUBRCBE","UHYWXJVK","QMHRQEHW","BSUUMNCW","ZGEBFJGE","UXUSXHDC","HTUQYZKY","PASKNEHA","NNCVUQET","WFRCVUJJ","VNPYHDNY","FZMXXQAB","XKRPNXNH","PNRCZUTZ","RXJQSWGK","XVZQDFAX","TTGMTGZG","RGZCTHNB","FMTKSYXT","NVWTEURM","RUSSJXSC","WNPTBNUR","XDFFKTDY","YZKNFCUJ","WTNPDXTJ","YYCURMJK","UMDYDBHB","WTUJQGQB","CYUXKBTM","GZWPHZME","KBJETSAC","XUVANEHH","JFADHFAH","RMKEDYAN","RBCRGDMD","JSGPBQHU","CTFQTXJB","GFXKJGQA","CYSEAQER","WNZEDRAG","PZFSWXQT","EQXDABRQ","GGERPPQW","CTSSBQZH","XCVBPVTP","UJEQGQBD","ZYYZVEMD","VMJSUQSE","JRDVGVCP","BUGMBSPQ","XNCKKKBY","HRFDACZV","FVZBRXZG","NHWUTMQZ","DFJWVMMX","JTJJBQQR","QVMHHCYR","PFMNJDKD","RHRBANRU","PYUGXYBQ","JBNJDWHV","KHHQUWGY","UMPMQAHM","GTYKJJKU","THTBVMCP","NWASHKCR","YZXSHBVT","NTABMBDT","FAUZQPVQ","KSTCWVTB","TEXWBUNM","BWRVSUDV","XHGZKRBC","TFFXTVCW","XJYGFAJF","JZUGHTWG","TEDQVEPT","RHKKZVEK","SFPEEQEC","CRUXUHEV","RYZRZYJE","AHVQJKMU","EAJNJAHM","YHMYBSTR","XGMKZEGQ","TAWQDMGD","VQUTVSHD","QSURVCDY","DZFWEMSC","WNYKRXPT","RNCQVXZX","DBWSWVZF","XDMWDZEA","PAHJSYQR","BWQTBEJW","TTZBHFCV","MFQVFPPJ","YPXEQJNG","QBWXUUQT","FHNFDXHW","YJYUUNKN","JXCWUCHJ","ZCJGUHWK","JJUSWZWS","RVVUEHSR","JPAQXGSJ","NXYCTNNG","HCMJCAPW","EDRZACSR","QZQFWGFN","YTZDXSEH","YFPHXCUC","DZTAUJJH","HHNWUNRT","JBSWCUFP","DKEKFCQT","JSXVDGMA","THUDCEKK","KSSSXUAC","HACWNVNH","JFQDNPSP","ZEGVWGAU","SBNJYBGK","MQZGJTJZ","QRZTCNVK","JGHGSQZR","PETUJRAN","UQZXVHPZ","WFZEQSYF","SNESJWCC","ECUWEGFE","VYUPRVHH","TFJBKFHD","ZRFTTUBJ","DQFYMTYK","WWPJVSDH","YJXZWVXT","BCMEDKRM","HUWZSGQM","DAUUWHFN","GKSXAFZX","VQNPPHXV","PWSVFQVE","NXZZJSVS","DJSAJUKJ","JHZARQYV","BHJGSZTZ","RAXMVANJ","HVWPSWXV","EZFRVPHD","ZNYAJFKH","GUSBFBVK","SHDKCUHD","WVQDSAJZ","UCZYYSHV","UTTMBHWJ","QPFSDSRH","PQYKGCFE","QKHZZTKG","REBSHZMK","ZZYKRCNR","FHKEANBA","RYFSSXEM","YKUTGPSS","FXJXKFQN","YYYJSCAN","WBPYQENW","WYKZDWNH","BBTEMQCM","GGPAGHAX","NHXCAARH","WKGTDXPQ","ZYXQKZPV","VQPYGAMV","FRQDPAHR","HPAVVKXR","UHVZWMBX","UVXDFXTP","HJDWQJNR","CJXUWYWJ","URAJWUTY","HDRJVTXH","UWHAJDCF","HXTBCTDD","QPEAHEUT","BQSJWPQU","MKTRXRCG","KTAPXGJC","SGAFVRET","BDGMJSHQ","GYSFQFDW","NWCVGZQW","NMZVHKCJ","FKNRYGTN","ACEMZWZN","GEDCZSTV","DSQXCYUF","VXYDGEDY","APRGMREM","RQXYTMMA","PCMFEHRK","XYBBWDFP","UUHVEMGK","HRVQBCZV","BZFKSJHE","JXXUKJVH","RYAQFWWM"
      )
      
      threeMonths.map { grouponCode =>
        Groupon.createNewGroupon(grouponCode, 3)
      }

      sixMonths.map { grouponCode =>
        Groupon.createNewGroupon(grouponCode, 6)
      }
    }
  }

  def updateParentNoPets = {
    val parents = User.findAll(By(User.userType, UserType.Parent), By(User.status, Status.Active))

    parents.map { parent =>
      val pets = parent.activePets

      if (pets.size == 0)
        parent.getSubscription.map(_.status(Status.UserSuspended).saveMe)
    }
  }

  def updateBlankPriceCode = {
    val subscriptions = Subscription.findAll()

    subscriptions.map { subscription =>
      if (subscription.priceCode.get == "default")
        subscription.priceCode("legacy").saveMe
    }
  }
}
