name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
       fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Get Shipstation API
      uses: riveramj/shipstation-scala
    - name: publishLocal
      run: sbt publishLocal
    - name: Setup Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.8"
    - name: Compile
      run: sbt compile
    - name: Run tests
      run: sbt coverage test
    - name: Coverage Report
      run: sbt coverageReport
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: d0f97166-4249-470b-bcd9-639d149e0f82
        fail_ci_if_error: true