name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
       fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: SBT Action
      id: sbt
      uses: lokkju/github-action-sbt@v8-0.13.17-2.13.0
      with:
        commands: compile test

